exclude: ^doc/source/
repos:
  - repo: https://github.com/psf/black
    rev: "24.4.2"
    hooks:
    - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
    - id: ruff
      args: ["--config=apis/python/pyproject.toml"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
    - id: mypy
      additional_dependencies:
        - pandas-stubs
        - "somacore @ git+https://github.com/single-cell-data/SOMA.git@e7b9379"   # DO NOT MERGE TO MAIN
        - types-setuptools
      args: ["--config-file=apis/python/pyproject.toml", "apis/python/src", "apis/python/devtools"]
      pass_filenames: false
